version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: imdb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
